spring:
  application:
    name: proyecto
  profiles:
    active: local

---
spring:
  profile: local
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cliente1
    username: postgres
    password: 1234
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: none
